size: 3086
assets-scale: 1

# PIXELS or PERCENT (of total image size)
position-mode: PERCENT

output-dir: "./out"
assets-dir: "./Assets"

background-color: "#00000000"
shadow-position: (0, 0.31)

# Assets with this sign in its name get the primary color
primary-color-sign: "%"
accent-color-sign: "&"
