size: 3086
assets-scale: 1

# PIXELS or PERCENT (of total image size)
position-mode: PIXELS

output-dir: "./out"
assets-dir: "./Assets"

background-color: "#d4c66e"
shadow-position: (0, 0.31)

# Everything with this hue gets recolored to the one specified by the attribute
color-placeholder-hue: 60  # 0=red, 120=green, 240=blue
